import type { Config } from "../../denops/hellshake-yano/types.ts";

export function createTestConfig(overrides: Partial<Config> = {}): Config {
  return {
    markers: ["A", "S", "D", "F", "G"],
    motion_count: 1,
    motion_timeout: 1000,
    hint_position: "end",
    trigger_on_hjkl: true,
    counted_motions: [],
    enabled: true,
    maxHints: 200,
    debounceDelay: 50,
    use_numbers: true,
    highlight_selected: true,
    debug_coordinates: false,
    visual_hint_position: "end",
    single_char_keys: ["A", "S", "D", "F"],
    multi_char_keys: ["J", "K", "L", ";"],
    max_single_char_hints: 4,
    use_hint_groups: true,
    use_japanese: false,
    word_detection_strategy: "hybrid",
    enable_tinysegmenter: false,
    segmenter_threshold: 3,
    japanese_min_word_length: 2,
    japanese_merge_particles: false,
    japanese_merge_threshold: 0,
    highlight_hint_marker: "HellshakeYanoMarker",
    highlight_hint_marker_current: "HellshakeYanoMarkerCurrent",
    suppress_on_key_repeat: false,
    key_repeat_threshold: 150,
    key_repeat_reset_delay: 200,
    per_key_min_length: {},
    default_min_word_length: 1,
    per_key_motion_count: {},
    default_motion_count: 1,
    current_key_context: undefined,
    min_word_length: 1,
    enable: true,
    debug_mode: false,
    performance_log: false,
    ...overrides,
  };
}
