# character-ranges.yml
# 文字範囲定義（CJK、絵文字、記号など）

# CJK文字範囲
cjk_ranges:
  - [0x3000, 0x303F]  # CJK Symbols and Punctuation
  - [0x3040, 0x309F]  # Hiragana
  - [0x30A0, 0x30FF]  # Katakana
  - [0x4E00, 0x9FFF]  # CJK Unified Ideographs
  - [0xFF00, 0xFFEF]  # Halfwidth and Fullwidth Forms

# 絵文字範囲
emoji_ranges:
  - [0x1F600, 0x1F64F]  # Emoticons
  - [0x1F300, 0x1F5FF]  # Miscellaneous Symbols and Pictographs
  - [0x1F680, 0x1F6FF]  # Transport and Map Symbols
  - [0x1F1E6, 0x1F1FF]  # Regional Indicator Symbols

# ラテン文字の数学記号範囲
latin_math_symbol_ranges:
  - [0x00B0, 0x00B1]  # Degree sign, Plus-minus sign
  - [0x00B7, 0x00B7]  # Middle dot
  - [0x00D7, 0x00D7]  # Multiplication sign
  - [0x00F7, 0x00F7]  # Division sign
  - [0x2190, 0x21FF]  # Arrows
  - [0x2200, 0x22FF]  # Mathematical Operators
  - [0x2300, 0x23FF]  # Miscellaneous Technical
  - [0x25A0, 0x25FF]  # Geometric Shapes
  - [0x2600, 0x26FF]  # Miscellaneous Symbols
  - [0x2700, 0x27BF]  # Dingbats

# 有効な記号リスト
valid_symbols:
  - ";"
  - ":"
  - "["
  - "]"
  - "'"
  - '"'
  - ","
  - "."
  - "/"
  - "\\"
  - "-"
  - "="
  - "`"

# ASCII文字範囲
ascii_range:
  start: 0x20  # Space
  end: 0x7E    # Tilde (~)
