# hint-keys.yml
# ヒントキー設定

# デフォルトマーカー
default_markers: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

# 単一文字キー（ホームポジション優先）
default_single_char_keys: "ASDFGHJKLNM0123456789"

# 複数文字キー
default_multi_char_keys: "BCEIOPQRTUVWXYZ"

# 数字キー（優先順位順）
numeric_keys:
  home_row: "789456123"  # ホームポジション数字（右手）
  top_row: "0"           # 上段数字

# キーグループ
key_groups:
  home_position:
    left_hand: "ASDF"
    right_hand: "JKL;"
  top_row: "QWERTYUIOP"
  middle_row: "ASDFGHJKL"
  bottom_row: "ZXCVBNM"

# 推奨設定
recommended:
  single_char_max: 20  # 単一文字ヒントの最大数
  multi_char_max: 100  # 複数文字ヒントの最大数
  numeric_enabled: true  # 数字ヒントの有効化
