# japanese-patterns.yml
# 日本語パターン定義

# 日本語助詞リスト（マージ対象）
japanese_particles:
  - "が"
  - "の"
  - "を"
  - "に"
  - "へ"
  - "と"
  - "より"
  - "から"
  - "で"
  - "や"
  - "は"
  - "も"

# 日本語助動詞リスト
japanese_auxiliary_verbs:
  - "だ"
  - "です"
  - "ます"
  - "である"
  - "でした"
  - "ました"

# 日本語特殊文字
japanese_special_chars:
  iteration_marks:
    - "々"  # 同じ字の繰り返し
    - "ゝ"  # ひらがなの繰り返し
    - "ゞ"  # ひらがなの濁点付き繰り返し
    - "ヽ"  # カタカナの繰り返し
    - "ヾ"  # カタカナの濁点付き繰り返し

  punctuation:
    - "。"  # 句点
    - "、"  # 読点
    - "・"  # 中黒
    - "「"  # 開きかぎ括弧
    - "」"  # 閉じかぎ括弧
    - "『"  # 開き二重かぎ括弧
    - "』"  # 閉じ二重かぎ括弧

# 日本語マージ設定
merge_settings:
  particles_enabled: true  # 助詞マージを有効化
  threshold: 2  # マージ閾値（文字数）
  max_merge_count: 3  # 最大マージ数

# TinySegmenter設定
tinysegmenter:
  enabled: true
  cache_size: 1000
  threshold: 1  # セグメンテーションの最小文字数
